### ISSUE TITLE
Course with SM=Manual not joined - Define what to display for its modules actions

### ISSUE THREAD

**Issue by mfernandagf** [Fielo-Plugins/fielocms-fieloelr#2]
If there is a course with subscription mode = manual that was not joined by the user yet, if we click this course name, its modules shows the action buttons as "LOADING..." indefinitely.
One of the possible solutions is to show a message: Join the course first.

![image](https://user-images.githubusercontent.com/26011197/28419026-339bfeac-6d34-11e7-8e7a-3f1d97639411.png)

**Comment by mfernandagf** [comment]
Now, the buttons are shown as "Take", but no action is taken when the member presses them.

**Comment by tibeal** [comment]
The problem is in these [lines](https://github.com/FieloIncentiveAutomation/fieloelr/blob/83abc1f99b63112b009cd737f4b0b449688293fc/src/classes/CourseService.cls#L361-L368). When there are no course status and module responses the first line is throwing null pointer exception.

We did a workaroud in order to fix it. But the code in the fieloelr repo must be corrected.

❗️ **Note:** For the Manual Subscription Courses, if the member did not join the course no action will be displayed for the Modules.
